### ISSUE TITLE
Building on Netlify fails

### ISSUE THREAD

**Issue by skorokithakis** [maxboeck/webring#4]
Thanks for this project, I love it! Unfortunately, cloning it and trying to get it building on Netlify fails:

```
Release/obj.target/libsass/src/libsass/src/values.o
3:34:39 PM:   rm -rf "Release/sass.a" && cp -af "Release/obj.target/src/sass.a" "Release/sass.a"
3:34:39 PM:   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/opt/buildhome/.node-gyp/12.18.0/include/node -I/opt/buildhome/.node-gyp/12.18.0/src -I/opt/buildhome/.node-gyp/12.18.0/deps/openssl/config -I/opt/buildhome/.node-gyp/12.18.0/deps/openssl/openssl/include -I/opt/buildhome/.node-gyp/12.18.0/deps/uv/include -I/opt/buildhome/.node-gyp/12.18.0/deps/zlib -I/opt/buildhome/.node-gyp/12.18.0/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
3:34:39 PM:   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/opt/buildhome/.node-gyp/12.18.0/include/node -I/opt/buildhome/.node-gyp/12.18.0/src -I/opt/buildhome/.node-gyp/12.18.0/deps/openssl/config -I/opt/buildhome/.node-gyp/12.18.0/deps/openssl/openssl/include -I/opt/buildhome/.node-gyp/12.18.0/deps/uv/include -I/opt/buildhome/.node-gyp/12.18.0/deps/zlib -I/opt/buildhome/.node-gyp/12.18.0/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
3:34:39 PM: ../src/create_string.cpp: In function ‘char* create_string(Nan::MaybeLocal<v8::Value>)’:
3:34:39 PM: ../src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
3:34:39 PM:    v8::String::Utf8Value string(value);
3:34:39 PM:                                      ^
3:34:39 PM: In file included from /opt/buildhome/.node-gyp/12.18.0/include/node/node.h:67:0,
3:34:39 PM:                  from ../../nan/nan.h:53,
3:34:39 PM:                  from ../src/create_string.cpp:1:
3:34:39 PM: /opt/buildhome/.node-gyp/12.18.0/include/node/v8.h:3135:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
3:34:39 PM:      Utf8Value(Isolate* isolate, Local<v8::Value> obj);
3:34:39 PM:      ^
3:34:39 PM: /opt/buildhome/.node-gyp/12.18.0/include/node/v8.h:3135:5: note:   candidate expects 2 arguments, 1 provided
3:34:39 PM: binding.target.mk:131: recipe for target 'Release/obj.target/binding/src/create_string.o' failed
3:34:39 PM: make: Leaving directory '/opt/build/repo/node_modules/node-sass/build'
3:34:39 PM: make: *** [Release/obj.target/binding/src/create_string.o] Error 1
3:34:39 PM: gyp ERR! build error
3:34:39 PM: gyp ERR! stack Error: `make` failed with exit code: 2
3:34:39 PM: gyp ERR! stack     at ChildProcess.onExit (/opt/build/repo/node_modules/node-gyp/lib/build.js:262:23)
3:34:39 PM: gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
3:34:39 PM: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
3:34:39 PM: gyp ERR! System Linux 4.14.138+
3:34:39 PM: gyp ERR! command "/opt/buildhome/.nvm/versions/node/v12.18.0/bin/node" "/opt/build/repo/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
3:34:39 PM: gyp ERR! cwd /opt/build/repo/node_modules/node-sass
3:34:39 PM: gyp ERR! node -v v12.18.0
3:34:39 PM: gyp ERR! node-gyp -v v3.8.0
3:34:39 PM: gyp ERR! not ok
3:34:39 PM: Build failed with error code: 1
3:34:39 PM: Error during Yarn install
3:34:39 PM: Error running command: Build script returned non-zero exit code: 1
3:34:39 PM: Failing build: Failed to build site
3:34:40 PM: Finished processing build request in 3m11.572235723s
```

This was a completely stock deploy, I didn't change any of the code.

**Comment by skorokithakis** [comment]
This seems related: https://github.com/nodejs/node-gyp/issues/1763

**Comment by sirodoht** [comment]
If anybody has the same issue, I've made a fork that eliminates yarn/gulp/node-sass from the codebase, so node-gyp it not needed for building the webring: https://github.com/sirodoht/webring

**Comment by skorokithakis** [comment]
I can confirm that the fork worked for me (maybe issue a PR?).

**Comment by sirodoht** [comment]
I'm unsure if a PR would suit the project author's preferences since it removes the Sass code structure. I did issue one just in case here: https://github.com/maxboeck/webring/pull/6

**Comment by maxboeck** [comment]
@skorokithakis thanks for your input! haven't looked into this for some time, so the build process was a bit out of date. appreciate the PR, but I would like to keep sass for now, so it's easier to customize the webring page.

I've updated dependencies and removed gulp from the build, it now processes Sass straight from within eleventy. Also switched from yarn to NPM. Netlify build with default settings should succeed now!

**Comment by skorokithakis** [comment]
Great, thank you!
